"""Bake data/participants.csv into network.html as static HTML.

Usage:  python build.py

Regenerates the content between the AUTO-GENERATED marker comments in
network.html (the participants table body and the fellow cohort lists).
Run this after every edit to data/participants.csv, then commit both files.
"""

import csv
import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent
CSV_PATH = ROOT / "data" / "participants.csv"
PAGE_PATH = ROOT / "network.html"

ROLE_LABELS = {"organizer": "Organizer", "senior": "Senior scholar", "fellow": "Junior Fellow"}


def surname(name: str) -> str:
    return name.split()[-1].lower()


def load_people() -> list[dict]:
    with open(CSV_PATH, encoding="utf-8-sig", newline="") as f:
        people = [{k.strip(): (v or "").strip() for k, v in row.items()}
                  for row in csv.DictReader(f)]
    return [p for p in people if p.get("display", "").upper() == "TRUE"]


def linked_name(p: dict, bold: bool = False) -> str:
    name = html.escape(p["name"])
    if p["website"]:
        return f'<a href="{html.escape(p["website"])}">{name}</a>'
    return f"<b>{name}</b>" if bold else name


def participants_rows(people: list[dict]) -> str:
    """Senior scholars only — organizers and fellows have their own tabs."""
    rows = []
    for p in sorted((p for p in people if p["role"] == "senior"),
                    key=lambda p: surname(p["name"])):
        rows.append(
            "        <tr>"
            f"<td>{linked_name(p)}</td>"
            f"<td>{html.escape(p['institution'])}</td>"
            "</tr>"
        )
    return "\n".join(rows)


def then_line(f: dict) -> str:
    """'2025 Fellow' plus the affiliation at the time when it differs from the current one."""
    line = f"{html.escape(f['cohort'])} Fellow"
    if f.get("current") and f["current"] != f["institution"]:
        line += f" · then {html.escape(f['institution'])}"
    return line


def fellow_card(f: dict) -> str:
    """Photo (assets/people/<photo>, or initials when blank), linked name, institution."""
    if f.get("photo"):
        pic = f'<img class="photo" src="assets/people/{html.escape(f["photo"])}" alt="{html.escape(f["name"])}">'
    else:
        initials = "".join(w[0] for w in f["name"].split()[:2]).upper()
        pic = f'<div class="avatar">{initials}</div>'
    return (
        '          <div class="person-card fellow">\n'
        f"            {pic}\n"
        f"            <h3>{linked_name(f)}</h3>\n"
        f"            <p>{html.escape(f.get('current') or f['institution'])}</p>\n"
        f'            <p class="then">{then_line(f)}</p>\n'
        "          </div>"
    )


def cohort_lists(people: list[dict]) -> str:
    fellows = [p for p in people if p["role"] == "fellow"]
    blocks = []
    for year in sorted({f["cohort"] for f in fellows}, reverse=True):
        cards = "\n".join(
            fellow_card(f)
            for f in sorted((f for f in fellows if f["cohort"] == year),
                            key=lambda f: surname(f["name"]))
        )
        blocks.append(
            f'      <div class="cohort">\n        <h3>{html.escape(year)} Cohort</h3>\n'
            f'        <div class="people-grid">\n{cards}\n        </div>\n      </div>'
        )
    return "\n".join(blocks)


def replace_section(page: str, marker: str, content: str) -> str:
    pattern = re.compile(
        rf"(<!-- BEGIN:{marker} \(auto-generated by build\.py — do not edit by hand\) -->)"
        rf".*?(<!-- END:{marker} -->)",
        re.DOTALL,
    )
    if not pattern.search(page):
        sys.exit(f"error: {marker} markers not found in {PAGE_PATH.name}")
    return pattern.sub(lambda m: f"{m.group(1)}\n{content}\n        {m.group(2)}", page)


def main() -> None:
    people = load_people()
    page = PAGE_PATH.read_text(encoding="utf-8")
    page = replace_section(page, "PARTICIPANTS", participants_rows(people))
    page = replace_section(page, "COHORTS", cohort_lists(people))
    PAGE_PATH.write_text(page, encoding="utf-8")
    fellows = sum(1 for p in people if p["role"] == "fellow")
    print(f"network.html updated: {len(people)} people listed ({fellows} fellows).")


if __name__ == "__main__":
    main()
